[package]
name = "chiper"
version = "0.1.0"
authors = ["f0rget <f0rget@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
