name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get -y install libsdl2-dev
    - name: FMT
      run: cargo --version && cargo fmt -v -- --check
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
